services:
  web:
    image: odoodev:15
    platform: linux/amd64
    container_name: o15
    depends_on:
      - mydb
    ports:
      - "8069:8069"
      - "8072:8072"
      - "8888:8888"
    volumes:
      - ./conf:/etc/odoo
      - ./custom-addons:/mnt/custom-addons
      - o15-data:/var/lib/odoo
      # - ./odoo:/usr/lib/python3/dist-packages/odoo # uncomment this if you want to mount odoo source code 
    entrypoint: /usr/bin/python3 -m debugpy --listen 0.0.0.0:8888 /usr/bin/odoo -c /etc/odoo/odoo.conf -d odoo -i base
  mydb:
    image: postgres:16
    platform: linux/amd64
    container_name: p16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - p16-data:/var/lib/postgresql/data/pgdata
volumes:
  o15-data:
  p16-data:
